Repository SashaRepin2/Lab_6_TRPO, pull requests merged in 2020-06, with the labels that each got.

#7 Библиотека
  PythonApplication1.sln
  PythonApplication1/PythonApplication1.py
  PythonApplication1/PythonApplication1.pyproj
  PythonApplication1/class1.py
Labels: trpo, visual studio

#8 Issue 4
  .travis.yml
  PythonApplication1/class1.py
  PythonApplication1/test_remotely.py
Labels: cl, trpo

#9 Update .travis.yml
  .travis.yml
Labels: cl, trpo

#10 Release
  .travis.yml
Labels: cl, trpo

#12 Pre-release
  .travis.yml
Labels: cl, trpo

#14 deploy pre-release
  README.md
Labels: cl

#18 Demo pre-release
  README.md
Labels: cl, trpo

#19 Update README.md
  README.md
Labels: cl

#21 Update .travis.yml
  .travis.yml
Labels: bug

#20 Update README.md
  README.md
Labels: cl, trpo
